---
- name: Initialize First Master Node
  hosts: masters
  become: yes
  tasks:

    - name: Gather facts
      ansible.builtin.setup:

    - name: Reset kubeadm (clean previous state)
      command: kubeadm reset -f
      register: kubeadm_reset
      failed_when: false
      changed_when: false
      
    - name: Display kubeadm reset output
      debug:
        msg: "{{ kubeadm_reset.stdout_lines }}"
      when: kubeadm_reset.stdout_lines is defined

    - name: Initialize Kubernetes control plane
      command: >
        kubeadm init
        --pod-network-cidr=192.168.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Ensure .kube directory exists for root
      file:
        path: /root/.kube
        state: directory
        owner: root
        group: root
        mode: '0700'

    - name: Copy admin.conf to root .kube/config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        owner: root
        group: root
        mode: '0600'
        remote_src: yes

    - name: Ensure .kube directory exists for ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0700'

    - name: Copy admin.conf to ubuntu user .kube/config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        group: ubuntu
        mode: '0600'
        remote_src: yes

    - name: Set KUBECONFIG environment variable for ubuntu user
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'export KUBECONFIG=$HOME/.kube/config'
        state: present
        create: yes

    - name: Ensure kubelet is enabled and started
      systemd:
        name: kubelet
        enabled: yes
        state: started

