---
- name: Join Worker Nodes
  hosts: workers
  become: yes
  gather_facts: yes
  serial: 1
  
  tasks:
    - name: Copy worker join command from localhost
      copy:
        src: "../join-commands/worker-join-command.sh"
        dest: "/tmp/worker-join-command.sh"
        mode: '0755'
        
    - name: Join worker to cluster
      shell: /tmp/worker-join-command.sh
      register: worker_join
      
    - name: Display worker join output
      debug:
        var: worker_join.stdout_lines
        
    - name: Wait for node to be ready
      shell: kubectl get node {{ inventory_hostname }} --no-headers | awk '{print $2}'
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      delegate_to: master1
      register: node_status
      until: node_status.stdout == "Ready"
      retries: 30
      delay: 10
