---
- name: Install Metrics Server
  hosts: master1
  become: true
  gather_facts: true
  vars_files:
    - ../vars/main.yml

  tasks:
    - name: Add metrics-server Helm repository
      shell: |
        helm repo add metrics-server {{ metrics_server_repository }}
        helm repo update
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: helm_repo_add
      changed_when: "'metrics-server' in helm_repo_add.stdout or 'has been added' in helm_repo_add.stdout"

    - name: Verify values file exists
      stat:
        path: "{{ metrics_server_values_file }}"
      register: values_file_stat
      delegate_to: localhost
      changed_when: false

    - name: Fail if values file does not exist
      fail:
        msg: "Values file not found at {{ metrics_server_values_file }}"
      when: not values_file_stat.stat.exists

    - name: Copy values file to master node
      copy:
        src: "{{ metrics_server_values_file }}"
        dest: /tmp/metrics-server-values.yaml
        mode: '0644'
      when: values_file_stat.stat.exists

    - name: Create namespace for Metrics Server
      shell: |
        kubectl create namespace {{ metrics_server_namespace }} --dry-run=client -o yaml | kubectl apply -f -
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: namespace_create
      changed_when: "'created' in namespace_create.stdout or 'configured' in namespace_create.stdout"

    - name: Install Metrics Server using Helm
      shell: |
        helm upgrade --install {{ metrics_server_release_name }} metrics-server/{{ metrics_server_chart }} \
          --namespace {{ metrics_server_namespace }} \
          --version {{ metrics_server_chart_version }} \
          --values /tmp/metrics-server-values.yaml \
          --wait \
          --timeout {{ helm_timeout }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: helm_install
      changed_when: "'STATUS: deployed' in helm_install.stdout or 'has been upgraded' in helm_install.stdout"

    - name: Display Helm installation output
      debug:
        var: helm_install.stdout_lines

    - name: Display Metrics Server deployment status (informational)
      shell: |
        kubectl get deployment -n {{ metrics_server_namespace }} {{ metrics_server_release_name }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: deployment_status
      changed_when: false
      failed_when: false

    - name: Show deployment status
      debug:
        var: deployment_status.stdout_lines
      when: deployment_status.rc == 0

