all:
  hosts:
    master1:
      ansible_host: 98.91.241.66
    worker1:
      ansible_host: 98.87.165.108
    worker2:
      ansible_host: 44.202.216.253
  children:
    masters:
      hosts:
        master1:
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: k8s-cluster-key
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    workers:
      hosts:
        worker1:
        worker2:
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: k8s-cluster-key
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

