all:
  hosts:
    master1:
      ansible_host: 34.229.43.118
    worker1:
      ansible_host: 54.81.155.35
    worker2:
      ansible_host: 3.231.204.47
  children:
    masters:
      hosts:
        master1:
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: k8s-cluster-key
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    workers:
      hosts:
        worker1:
        worker2:
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: k8s-cluster-key
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

